import React from "react";
import { createTheme, ThemeProvider } from '@mui/material/styles';
// import { makeStyles } from '@mui/styles';
import { Typography, Card } from '@mui/material';

import { styled } from '@mui/system';

const MyDiv = styled('Typography')({
  color: '#ff4400',
  backgroundColor: 'aliceblue',
  padding: 8,
  borderRadius: 4,
  display: 'block', 
  textAlign: 'left', 
  fontSize: 34, 
});

export default function RootKeyInfo(props){

    return(
        <Card>
        <Typography variant="h2" align="left">Root Key</Typography> 
        
        <MyDiv> Each session contains a growing array of Root keys. </MyDiv>
        <MyDiv> Root keys are not used directly: they are used to derive other keys. </MyDiv>
        <MyDiv> The rootkeys are the same for both clients, except one client's array may be longer than the other client.</MyDiv>
        <MyDiv> A client's root key array grows when it receives and decrypts message, or when it sends out the first message.</MyDiv>        
        <MyDiv> Each new root key is derived from the previous root key and fresh entropy jointly generated by both clients. </MyDiv> 
        </Card>
    )
}